Ljg
2023-Capstone/capstone-back pull request #3
Opened 2023-05-02 13:25 UTC by JaeGeon-SMU

1. 코드 추가/변경 이유가 무엇인지?
pull request 실험
2. 코드 주요 구현 사항이 무엇인지?
s3 이미지 서버에 파일 업로드
3. 리뷰어가 확인할 사항, 전달사항

2023-05-04 04:12 UTC, 2ralumin approved these changes

2023-05-04 04:12 UTC, 2ralumin approved these changes

2023-05-04 04:12 UTC, 2ralumin approved these changes

2023-05-04 04:13 UTC, 2ralumin approved these changes

2023-05-06 15:41 UTC, jyzayu requested changes
👍수정 필요
 전반적으로 project 설정이 달라서  merge된 제 프로젝트에 
src파일을 새로 복사 붙이기 해야 할 것 같습니다. 

pull request 올리기전에 issue 생성하기  -- 깃헙 규칙 
pull request할 때 branch 이름이 feat/4? 이런 식으로 되야 할듯 

깃헙 규칙은 모르겠는데  프로젝트 구조는  수정해야 할 것 같습니다.
서비스 기업에서 깃헙도 잘 본다고는 하는데 뭐 오래걸리는 건 아닌 것 같아요,
노션에 있는 깃헙 규칙 봐보는 것도 좋을 것 같습니다. 

- [] S3testApplication.java 삭제하고,
- [] AmazonS3Config , 는 globla/config/s3  경로로 이동시키고,    S3Uploader(?)
- [] 그리고 인증 기능구현하면서 application.yml 파일이 있을텐데  
- [] application-s3.yml 정도로 파일 이름을 바꾸는게 좋아보임 
application.yml이 application.properties를 다른 형식으로 나타낸 것이라 
지금 작성한 properties파일을 yml파일에 맞게 작성후? 혹은 ? properties파일로 되나 ?
- [] src/main/domain/diary 경로로 Diary 파일들 옮겨야 해보임 
- 그리고 .gitignore에 추가한 파일이 있다면 알려주세요.
- build,gralde은 겹치는데 어떻게 해야하지? 
-

2023-05-09 09:41 UTC, closed without merging